### ISSUE TITLE
broken image links

### ISSUE THREAD

**Issue by unknown321** [wildfly/wildfly.github.io#5]
http://docs.wildfly.org/15/Admin_Guide.html#managed-domain

There should be an image after `The following is an example managed domain topology:`, but images links are broken - http://docs.wildfly.org/15/images/images/DC-HC-Server.png instead of http://docs.wildfly.org/15/images/DC-HC-Server.png

**Comment by bstansberry** [comment]
I filed https://issues.jboss.org/browse/WFLY-11705 for this. Thanks.
